### ISSUE TITLE
Updated configuration

### ISSUE THREAD

**Issue by Fanus** [heavenshell/vim-slack#4]
Please send updated configuration (.vimrc) of how to get this working. When I try post a message using :Slack nothing happens. I've setup the hook properly, just need to generate the correct payload.

**Comment by heavenshell** [comment]
@Fanus
Oops sorry.
It did not work.

I Fixed it.
Could you check?

Sample vimrc settings is followings.

``` viml
let g:slack_channels = {
    \ '#random': 'https://YOUR_TEAM.slack.com/services/hooks/incoming-webhook?token=YOUR_TOKEN'
  \}
```

**Comment by fanmanpro** [comment]
Works perfectly.
Thank you :)

**Comment by heavenshell** [comment]
Nice catch! Thanks!
